enchantmentDamage:
  power:
    scale: 0.4
  flame:
    '1': 0.4
    scale: 2.0
  infinity:
    '1': 0.8
  punch:
    scale: 0.4
  binding_curse:
    '1': -2.0
  sharpness:
    scale: 0.15
  bane_of_arthropods:
    scale: 0.125
  smite:
    scale: 0.125
  efficiency:
    scale: 0.3
  unbreaking:
    scale: 0.2
  fire_aspect:
    scale: 0.5
  knockback:
    scale: 0.5
  fortune:
    scale: 1.5
  looting:
    scale: 0.5
  luck_of_the_sea:
    scale: 2.7
  lure:
    scale: 2.0
  mending:
    '1': 3.0
  protection:
    scale: 0.4
  blast_protection:
    scale: 0.2
  feather_falling:
    scale: 0.2
  fire_protection:
    scale: 0.2
  projectile_protection:
    scale: 0.2
  silk_touch:
    '1': 1.0
  sweeping:
    scale: 0.05
  vanishing_curse:
    '1': -1.0
materialScales:
  IRON_SHOVEL: 0.5
  IRON_PICKAXE: 0.5
  IRON_AXE: 0.5
  IRON_HOE: 0.5
  IRON_SWORD: 0.5
  GOLDEN_SHOVEL: 0.0
  GOLDEN_PICKAXE: 0.0
  GOLDEN_AXE: 0.0
  GOLDEN_HOE: 0.0
  GOLDEN_SWORD: 0.0
  STONE_SHOVEL: 0.25
  STONE_PICKAXE: 0.25
  STONE_AXE: 0.25
  STONE_HOE: 0.25
  STONE_SWORD: 0.25
  WOODEN_SHOVEL: 0.0
  WOODEN_PICKAXE: 0.0
  WOODEN_AXE: 0.0
  WOODEN_HOE: 0.0
  WOODEN_SWORD: 0.0
  DIAMOND_HELMET: 0.6
  DIAMOND_CHESTPLATE: 0.6
  DIAMOND_LEGGINGS: 0.6
  DIAMOND_BOOTS: 0.6
  IRON_HELMET: 0.2
  IRON_CHESTPLATE: 0.2
  IRON_LEGGINGS: 0.2
  IRON_BOOTS: 0.2
  GOLDEN_HELMET: 0.0
  GOLDEN_CHESTPLATE: 0.0
  GOLDEN_LEGGINGS: 0.0
  GOLDEN_BOOTS: 0.0
  BOW: 0.8
  FISHING_ROD: 0.2
